name: time-extended
version: '0.0.1'
synopsis: Haskell project time-extended repo
description: <https://github.com/tonyday567/time-extended>
maintainer: Tony Day <tonyday567@gmail.com>
license: MIT
license-file: LICENSE.md
bug-reports: https://github.com/tonyday567/time-extended/issues
extra-source-files:
- README.md
dependencies:
- base ==4.*
- attoparsec
- binary
- bytestring
- containers
- formatting
- old-locale
- text
- time
- timezone-series
library:
  source-dirs: src
  exposed-modules:
  - Data.Time.Extended
